### ISSUE TITLE
3D Grid Import

### ISSUE THREAD

**Issue by jr144393** [gdtk-uq/gdtk#20]
To Whom It May Concern,

In importing a 3d test grid (in this case just a box with a mesh generated in GMSH (with .su2 format), I experience issues with the prep command which references gdtk/build/lib/blk_conn.lua - with attempt to index a nil value (field 'p'). I am trying to trace back the error. Is this a grid import or formatting error? I feel as though the error is in my process, but that this information may be useful for others in the future. I have attached the grid and geo file for reference. 

I have successfully taken a 3d geometry into GMSH and performed a slicing operation on it in GMSH - that 2D slice mesh file reads into Eilmer without issue, and I am attempting a similar procedure in this case with the main difference being that I am leaving the full 3d mesh in place. 

Thank you for your attention to this issue. If I can provide more information about the method I have been trying that will assist in resolving this please let me know. 

[BoxTest2.zip](https://github.com/gdtk-uq/gdtk/files/10482717/BoxTest2.zip)

**Comment by uqngibbo** [comment]
Hi jr,

Lua scripts often fail with this error. It usually means that you've forgotten to assign a value to the variable p, which leaves it with the default value of 'nil'. Trying to then do an operation on a nil value causes the error.

Most likely this is an issue with your prep script. Please check it creafully, and, if you can't figure out what's wrong, consider uploading it and I can take a look.

**Comment by jr144393** [comment]
I believe I have found my issue. Thank you for your attention.

**Comment by uqngibbo** [comment]
That's great to hear!
