### ISSUE TITLE
Simulating Shock Tunnel with 2-D Contour Nozzle (not conical nozzle) in L1d3

### ISSUE THREAD

**Issue by darshan1664** [gdtk-uq/gdtk#26]
Hii, 

I am doing experimental Research on shock tube and shock tunnel systems. To get an estimation of expected results, I want to simulate flow in our shock tunnel which uses a 2-D contour nozzle (see images attached). The nozzle includes a convergent section, throat, divergent section and then a constant area section. The 2-D drawing shows these parts with respective dimensions (the dimensions are in cm). The 3d drawing illustrates the divergent part and throat. And the 3d assembly drawing shows nozzle configuration which will be fitted behind the shock tube to make it a shock tunnel. The area ratio (exit area/throat area) of this contour nozzle is equal to 0.012/0.08 = 6.667. The throat height is 0.012 meters, the exit height is 0.08 meters, and the thickness of the nozzle (perpendicular to the plane of the paper) is 0.04 meters. One thing to note is that the convergent section is a circular arc, hence the convergent section can be treated as a conical convergent section. So that was a basic information about the nozzle. 

Now, the question is: How can I simulate it in L1d3? To the best of my knowledge, when we add two breakpoints in L1d, it uses linear interpolation to join them. This method will work for the 3-D conical nozzle because, in the 2-D projection, it will appear that the throat and the exit are attached in a linear fashion, also the throat and exit of a conical nozzle are actually circles, hence they can be completely defined by diameter value given in the add_breakpoint command. However, this is not the case with a 2-D contour nozzle. Its geometry will be different in the 2-D plane, and the throat and the exit are not attached with a linear line. Also, the throat and exit are rectangular in shape, so if we give value of their heights in place of diameter in add_breakpoint command, their area ratio will be completely different (L1d will be take them as circular section with those height values a diameter). So, how can I simulate this 2-D contour nozzle in L1d? The most important requirement is that the area ratio should not change while defining the geometry.

Looking forward for suggestions..... 

![2d](https://github.com/gdtk-uq/gdtk/assets/129246592/c87ad41d-dbac-4387-910b-5c206c72f765)
![3d_nozzle](https://github.com/gdtk-uq/gdtk/assets/129246592/e201f9e1-24fe-4037-8ef9-73cc9fc626d9)
![nozzle_assembly](https://github.com/gdtk-uq/gdtk/assets/129246592/ffff00b3-dd9b-441a-9dee-2ea38d99720e)

**Comment by pajacobs-ghub** [comment]
The core gas-dynamic model in L1d cares only about the axial wave processes in a tube of varying area.  The shape of the cross-section is not considered.  We just happen to specify that area via diameter values.  If that model is useful to you, just define a circular-cross-section duct with equivalent area variation to your nozzle and compute away.  If you care about the multi-dimensional gas processes, use Eilmer instead.
