### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by wxkkkzs** [gdtk-uq/gdtk#31]
Dear all，

I have an issue when I install the code on Ubuntu.
I've installed ldc and configured environment variables in .bashrc.
But when I make install in \gdtk\src\eilmer the following error occurs, I tried it on another computer but got the same error.

I'd really appreciate some help with this!

Thanks!
Cheers,
Xinke Wang from NSSC

~/gdtk/src/eilmer$ make install
sed -e 's/PUT_REVISION_STRING_HERE/fe3e854e/' \
	-e 's/PUT_REVISION_DATE_HERE/Sat Jul 15 14:07:15 2023 +1000/' \
	-e 's/PUT_COMPILER_NAME_HERE/ldc2/' \
	-e 's/PUT_BUILD_DATE_HERE/2023年 07月 17日 星期一 11:24:18 CST/' \
	main.d > main_with_rev_string.d
ldc2 -w -g -link-defaultlib-debug -L-export-dynamic -d-debug -d-version=flavour_debug  -dip1008 -preview=in -I.. -I../nm -I../util -I../geom -I../grid_utils -I../extern/gzip -d-version=multi_species_gas -d-version=multi_T_gas -d-version=MHD -d-version=turbulence -of=e4shared \
	-d-version=tecplot_unavailable \
	main_with_rev_string.d \
	simcore.d simcore_gasdynamic_step.d simcore_solid_step.d simcore_exchange.d simcore_io.d fileutil.d fvcell.d fvvertex.d fvinterface.d fluxcalc.d onedinterp.d flowgradients.d lsqinterp.d conservedquantities.d flowstate.d globalconfig.d globaldata.d block.d fluidblock.d sfluidblock.d ufluidblock.d fluidblockarray.d fluidblockio_old.d fluidblockio_new.d gas_solid_interface.d grid_motion.d grid_motion_udf.d grid_motion_shock_fitting.d history.d loads.d special_block_init.d mass_diffusion.d shockdetectors.d turbulence.d jacobian.d fluidblockio.d celldata.d lua_helper.d luaflowsolution.d luaflowstate.d user_defined_source_terms.d postprocess.d flowsolution.d vtk_writer.d tecplot_writer_classic.d tecplot_writer.d \
	bc/package.d bc/boundary_condition.d bc/ghost_cell_effect/package.d bc/ghost_cell_effect/ghost_cell.d bc/ghost_cell_effect/internal_copy_then_reflect.d bc/ghost_cell_effect/flow_state_copy.d bc/ghost_cell_effect/flow_state_copy_from_profile.d bc/ghost_cell_effect/flow_state_copy_from_history.d bc/ghost_cell_effect/synthesise_flow_state.d bc/ghost_cell_effect/extrapolate_copy.d bc/ghost_cell_effect/from_upwind.d bc/ghost_cell_effect/fixed_p.d bc/ghost_cell_effect/fixed_pt.d bc/ghost_cell_effect/from_stagnation.d bc/ghost_cell_effect/full_face_copy.d bc/ghost_cell_effect/mapped_cell_copy.d bc/ghost_cell_effect/gas_solid_full_face_copy.d bc/user_defined_effects.d bc/boundary_flux_effect.d bc/boundary_cell_effect.d bc/boundary_interface_effect.d solid/solidbc.d solid/solidblock.d solid/solid_ghost_cell.d solid/solid_boundary_flux_effect.d solid/solid_boundary_interface_effect.d solid/solid_gas_full_face_copy.d solid/solid_full_face_copy.d solid/ssolidblock.d solid/solidfvcell.d solid/solidfvinterface.d solid/solidfvvertex.d solid/solidprops.d solid/solidsolution.d solid/solid_udf_source_terms.d solid/luasolidprops.d field/field.d field/fieldgmres.d field/fieldconductivity.d field/fieldexchange.d field/fieldderivatives.d field/fieldbc.d ../geom/package.d ../geom/geometry_exception.d ../geom/elements/package.d ../geom/elements/nomenclature.d ../geom/elements/vector3.d ../geom/elements/properties.d ../geom/elements/projection.d ../geom/gpath/package.d ../geom/gpath/path.d ../geom/gpath/line.d ../geom/gpath/arc.d ../geom/gpath/helix.d ../geom/gpath/bezier.d ../geom/gpath/nurbs.d ../geom/gpath/polynomial.d ../geom/gpath/polyline.d ../geom/gpath/xspline.d ../geom/gpath/xsplinelsq.d ../geom/gpath/svgpath.d ../geom/gpath/modifiedpath.d ../geom/gpath/gpath_utils.d ../geom/surface/package.d ../geom/surface/parametricsurface.d ../geom/surface/coonspatch.d ../geom/surface/aopatch.d ../geom/surface/gmopatch.d ../geom/surface/channelpatch.d ../geom/surface/ruledsurface.d ../geom/surface/nozzleexpansionpatch.d ../geom/surface/sweptpathpatch.d ../geom/surface/meshpatch.d ../geom/surface/subrangedsurface.d ../geom/surface/bezierpatch.d ../geom/surface/beziertrianglepatch.d ../geom/surface/nurbssurface.d ../geom/surface/spherepatch.d ../geom/surface/cubepatch.d ../geom/surface/controlpointpatch.d ../geom/volume/package.d ../geom/volume/parametricvolume.d ../geom/volume/tfivolume.d ../geom/volume/slabvolume.d ../geom/volume/wedgevolume.d ../geom/volume/sweptsurfacevolume.d ../geom/volume/twosurfacevolume.d ../geom/volume/meshvolume.d ../geom/volume/subrangedvolume.d ../geom/volume/nurbsvolume.d ../geom/grid/package.d ../geom/grid/grid.d ../geom/grid/sgrid.d ../geom/grid/usgrid.d ../geom/grid/paver.d ../geom/grid/paver2d.d ../geom/misc/package.d ../geom/misc/univariatefunctions.d ../geom/misc/svg.d ../geom/misc/kdtree.d ../geom/misc/sketch.d ../geom/misc/nurbs_utils.d ../geom/luawrap/package.d ../geom/luawrap/luaunifunction.d ../geom/luawrap/luageom.d ../geom/luawrap/luanomenclature.d ../geom/luawrap/luagpath.d ../geom/luawrap/luagpath_utils.d ../geom/luawrap/luasurface.d ../geom/luawrap/luavolume.d ../geom/luawrap/luagrid.d ../geom/luawrap/luasgrid.d ../geom/luawrap/luausgrid.d ../geom/luawrap/luasketch.d ../grid_utils/grid_deform.d  \
	../gas/package.d ../gas/composite_gas.d ../gas/gas_model.d ../gas/gas_state.d ../gas/init_gas_model.d ../gas/ideal_gas.d ../gas/ideal_helium.d ../gas/cubic_gas.d ../gas/cea_gas.d ../gas/physical_constants.d ../gas/therm_perf_gas.d ../gas/therm_perf_gas_equil.d ../gas/very_viscous_air.d ../gas/uniform_lut.d ../gas/uniform_lut_plus_ideal.d ../gas/adaptive_lut_CEA.d ../gas/ideal_air_proxy.d ../gas/ideal_gas_ab.d ../gas/two_temperature_reacting_argon.d ../gas/two_temperature_argon_plus_ideal.d ../gas/ideal_dissociating_gas.d ../gas/two_temperature_air.d ../gas/two_temperature_nitrogen.d ../gas/two_temperature_dissociating_nitrogen.d ../gas/vib_specific_nitrogen.d ../gas/vib_specific_co.d ../gas/fuel_air_mix.d ../gas/equilibrium_gas.d ../gas/pseudo_species_gas.d ../gas/pseudo_species.d ../gas/electronically_specific_gas.d ../gas/electronic_species.d ../gas/two_temperature_gasgiant.d ../gas/thermo/cea_thermo_curves.d ../gas/thermo/evt_eos.d ../gas/thermo/perf_gas_mix_eos.d ../gas/thermo/pvt_eos.d ../gas/thermo/therm_perf_gas_mix_eos.d ../gas/thermo/thermo_model.d ../gas/thermo/therm_perf_gas_mix.d ../gas/thermo/two_temperature_gas.d ../gas/thermo/three_temperature_gas.d ../gas/thermo/multi_temperature_gas.d ../gas/thermo/energy_modes.d ../gas/diffusion/cea_therm_cond.d ../gas/diffusion/cea_viscosity.d ../gas/diffusion/chemkin_therm_cond.d ../gas/diffusion/chemkin_viscosity.d ../gas/diffusion/gas_mixtures.d ../gas/diffusion/sutherland_therm_cond.d ../gas/diffusion/sutherland_viscosity.d ../gas/diffusion/therm_cond.d ../gas/diffusion/transport_properties_model.d ../gas/diffusion/two_temperature_trans_props.d ../gas/diffusion/multi_temperature_trans_props.d ../gas/diffusion/three_temperature_trans_props.d ../gas/diffusion/viscosity.d ../gas/diffusion/wilke_mixing_therm_cond.d ../gas/diffusion/wilke_mixing_viscosity.d ../gas/diffusion/gasgiant_transport_properties.d ../gas/diffusion/binary_diffusion_coefficients.d ../gas/diffusion/rps_diffusion_coefficients.d ../extern/ceq/source/ceq.d ../extern/gzip/gzip.d \
	../util/lua.d ../util/json_helper.d ../util/lua_service.d ../util/msg_service.d ../util/time_utils.d ../util/zip.d ../nm/package.d ../nm/nm_exception.d ../nm/number.d ../nm/complex.d ../nm/bbla.d ../nm/bdfLU.d ../nm/bracketing.d ../nm/brent.d ../nm/secant.d ../nm/gaussquad.d ../nm/linesearch.d ../nm/nelmin.d ../nm/newton.d ../nm/newtoncotes.d ../nm/ridder.d ../nm/rungekutta.d ../nm/rsla.d ../nm/schedule.d ../nm/smla.d ../nm/stmatrix.d ../nm/tree_patch.d ../nm/univariate_lut.d ../nm/limiters.d ../nm/spline.d ../nm/splinelsq.d \
	../kinetics/package.d ../kinetics/thermochemical_reactor.d ../kinetics/init_thermochemical_reactor.d ../kinetics/chemistry_update.d ../kinetics/energy_exchange_mechanism.d ../kinetics/energy_exchange_system.d ../kinetics/equilibrium_update.d ../kinetics/electronic_update.d ../kinetics/electronically_specific_kinetics.d ../kinetics/ideal_dissociating_gas_kinetics.d ../kinetics/fuel_air_mix_kinetics.d ../kinetics/powers_aslam_kinetics.d ../kinetics/yee_kotov_kinetics.d ../kinetics/rate_constant.d ../kinetics/reaction.d ../kinetics/reaction_mechanism.d ../kinetics/relaxation_time.d ../kinetics/exchange_cross_section.d ../kinetics/exchange_chemistry_coupling.d ../kinetics/multi_temperature_thermochemical_reactor.d ../kinetics/two_temperature_air_kinetics.d ../kinetics/two_temperature_argon_kinetics.d ../kinetics/two_temperature_argon_with_ideal_gas.d ../kinetics/two_temperature_nitrogen_kinetics.d ../kinetics/two_temperature_dissociating_nitrogen_kinetics.d ../kinetics/vib_specific_nitrogen_kinetics.d ../kinetics/vib_specific_co_kinetics.d ../kinetics/two_temperature_gasgiant_kinetics.d ../gas/luagas_model.d ../kinetics/luathermochemical_reactor.d ../kinetics/luachemistry_update.d ../kinetics/luaequilibrium_calculator.d ../kinetics/luaelectronically_specific_kinetics.d ../kinetics/luareaction_mechanism.d ../kinetics/luatwo_temperature_air_kinetics.d ../kinetics/luavib_specific_nitrogen_kinetics.d \
	../gasdyn/gasflowexception.d ../gasdyn/idealgasflow.d ../gasdyn/gasflow.d ../gasdyn/luaidealgasflow.d ../gasdyn/luagasflow.d ../nm/luabbla.d  \
	../extern/ceq/source/libceq.a ../gas/libgasf.a ../../extern/lua-5.4.3/install/lib/liblua.a \
	 -L-ldl
Error: Preview `in` is invalid
make: *** [makefile:592：e4shared] 错误 1

**Comment by pajacobs-ghub** [comment]
Xinke,
What is the result of the command "ldc2 --version"?  My first guess is that you are using an old compiler.
Peter J.

**Comment by wxkkkzs** [comment]
Hi peter,
The version of my ldc is 1.20.1.

~/gdtk/src/eilmer$ ldc2 -version
LDC - the LLVM D compiler (1.20.1):
  based on DMD v2.090.1 and LLVM 10.0.0
  built with LDC - the LLVM D compiler (1.20.1)
  Default target: x86_64-pc-linux-gnu
  Host CPU: (unknown)
  http://dlang.org - http://wiki.dlang.org/LDC

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    amdgcn     - AMD GCN GPUs
    arm        - ARM
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    armeb      - ARM (big endian)
    avr        - Atmel AVR Microcontroller
    bpf        - BPF (host endian)
    bpfeb      - BPF (big endian)
    bpfel      - BPF (little endian)
    hexagon    - Hexagon
    lanai      - Lanai
    mips       - MIPS (32-bit big endian)
    mips64     - MIPS (64-bit big endian)
    mips64el   - MIPS (64-bit little endian)
    mipsel     - MIPS (32-bit little endian)
    msp430     - MSP430 [experimental]
    nvptx      - NVIDIA PTX 32-bit
    nvptx64    - NVIDIA PTX 64-bit
    ppc32      - PowerPC 32
    ppc64      - PowerPC 64
    ppc64le    - PowerPC 64 LE
    r600       - AMD GPUs HD2XXX-HD6XXX
    riscv32    - 32-bit RISC-V
    riscv64    - 64-bit RISC-V
    sparc      - Sparc
    sparcel    - Sparc LE
    sparcv9    - Sparc V9
    systemz    - SystemZ
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    wasm32     - WebAssembly 32-bit
    wasm64     - WebAssembly 64-bit
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
    xcore      - XCore

**Comment by pajacobs-ghub** [comment]
Xinke,
That would be the problem.  You can get a more recent ldc compiler from https://github.com/ldc-developers/ldc/releases
Cheers,
Peter J.

**Comment by wxkkkzs** [comment]
Peter,
The problem has been solved by this way.
Thank you for your help.

cheers,
Xinke Wang.
