### ISSUE TITLE
problem about "Flow of nitrogen over a cylinder of finite length"

### ISSUE THREAD

**Issue by wxkkkzs** [gdtk-uq/gdtk#34]
Dear all,

I have some issues when I run the example code in the folder "gdtk\examples\eilmer\3D\cylinder-troy-x2".

1.When I excute this command:
$ e4shared --prep --job=cyl
there is an error occur:
(base) wxk@wxk-virtual-machine:~/gdtk/examples/eilmer/3D/cylinder-troy-x2$ e4shared --prep --job=cyl
Eilmer 4.0 compressible-flow simulation code.
Revision-id: fe3e854e
Revision-date: Sat Jul 15 14:07:15 2023 +1000
Compiler-name: ldc2
Build-date: 2023年 07月 18日 星期二 14:19:42 CST
Build-flavour: debug
Profiling: omitted
Capabilities: multi-species-gas multi-temperature-gas MHD turbulence.
Parallelism: Shared-memory
Begin preparation stage for a simulation.
Loading prep.lua...
Done loading prep.lua
Cylinder L/D=2 in N2 at u=10000 m/s.
GasModel set nsp=   2    nmodes=    0
T=  3000.0  density=    0.002246145593667   sound speed=    1071.5671268405
M_inf=  9.3321265178087
-----a= Vector3(-0.0075, 0, 0)
There was a problem in the user-supplied input lua script: cyl.lua
globalconfig.FlowSolverException@main_with_rev_string.d(480): cannot open billig.lua: No such file or directory
----------------
main_with_rev_string.d:480 _Dmain [0x56050a77ad3a]

I think this error is related to the function call, so I modified billig.lua as follows.
![image](https://github.com/gdtk-uq/gdtk/assets/97238826/8935ac58-6b92-4ab0-88f6-279aec81ad0e)
I also modified the call command for billig.lua in cyl.lua.
![image](https://github.com/gdtk-uq/gdtk/assets/97238826/c6ed8b7f-d0c8-40d0-88b4-a0dee708a843)

then I successfully excute this command.
(base) wxk@wxk-virtual-machine:~/gdtk/examples/eilmer/3D/cylinder-troy-x2$ e4shared --prep --job=cyl
Eilmer 4.0 compressible-flow simulation code.
Revision-id: fe3e854e
Revision-date: Sat Jul 15 14:07:15 2023 +1000
Compiler-name: ldc2
Build-date: 2023年 07月 18日 星期二 14:19:42 CST
Build-flavour: debug
Profiling: omitted
Capabilities: multi-species-gas multi-temperature-gas MHD turbulence.
Parallelism: Shared-memory
Begin preparation stage for a simulation.
Loading prep.lua...
Done loading prep.lua
Cylinder L/D=2 in N2 at u=10000 m/s.
GasModel set nsp= 	2	 nmodes= 	0
T=	3000.0	density=	0.002246145593667	sound speed= 	1071.5671268405
M_inf=	9.3321265178087
Points on Billig's correlation.
x=	0.01056853277522	y=	0.0
x=	0.010106030042078	y=	0.00375
x=	0.0087195860834211	y=	0.0075
x=	0.0064123814146518	y=	0.01125
x=	0.0031896765302903	y=	0.015
x=	-0.00094124752002355	y=	0.01875
front of grid: d[1]=	Vector3(-0.00919462, 0, 0)
max_time=	2.25e-05
Build config files for job:	cyl
Done building config files.
NOTE: shock detector is on.
NOTE: shock detector is on.
Done building grid and flow files.
Done.

2.when I excute next command "e4shared --run --job=cyl --verbosity=1 --max-cpus=4", there is a new error as follow.
I have tried adjusting the mesh and solver, but this issue has not been resolved and will only have small impact on "fabs(massf_sum - 1.0)".
I don't know if the cause of this problem is physical or simulated, and it may also be related to my modification of billig.lua.

I'd really appreciate some help with this!

Thanks!
Cheers,
Xinke Wang from NSSC

(base) wxk@wxk-virtual-machine:~/gdtk/examples/eilmer/3D/cylinder-troy-x2$ e4shared --run --job=cyl --verbosity=1 --max-cpus=4
Eilmer 4.0 compressible-flow simulation code.
Revision-id: fe3e854e
Revision-date: Sat Jul 15 14:07:15 2023 +1000
Compiler-name: ldc2
Build-date: 2023年 07月 18日 星期二 14:19:42 CST
Build-flavour: debug
Profiling: omitted
Capabilities: multi-species-gas multi-temperature-gas MHD turbulence.
Parallelism: Shared-memory
Begin simulation with command-line arguments.
  jobName: cyl
  tindxStart: 0
  maxWallClock: 432000
  verbosityLevel: 1
  maxCPUs: 4 for shared memory-parallelism
Begin init_simulation()...
NOTE: shock detector is on.
Single process running with 4 threads.
Heap memory used: 532 MB, unused: 119 MB, total: 651 MB (651-651 MB per task)
Done init_simulation() at wall-clock(WC)= 9.4 sec
starting simulation time= 0
Integrate in time.
Exception thrown in phase 05a of stage 1 of explicit update: Sum of species mass fractions far from 1.0: fabs(massf_sum - 1.0) = 0.118622 
  assert_error_tolerance = 0.1 
  tolerance = 0 
  massf = [ 1.118622e+00 0.000000e+00]

Exception thrown in phase 05a of stage 1 of explicit update: Sum of species mass fractions far from 1.0: fabs(massf_sum - 1.0) = 0.118622 
  assert_error_tolerance = 0.1 
  tolerance = 0 
  massf = [ 1.118622e+00 0.000000e+00]

Exception thrown in phase 05a of stage 1 of explicit update: Sum of species mass fractions far from 1.0: fabs(massf_sum - 1.0) = 0.118622 
  assert_error_tolerance = 0.1 
  tolerance = 0 
  massf = [ 1.118622e+00 0.000000e+00]

Exception caught while trying to take step 1.
----- Begin exception message -----
globalconfig.FlowSolverException@simcore_gasdynamic_step.d(1542): Explicit update failed after 3 attempts; giving up.
----------------
simcore_gasdynamic_step.d:1542 void simcore_gasdynamic_step.gasdynamic_explicit_increment_with_fixed_grid() [0x561c679b8b2e]
simcore.d:1068 int simcore.integrate_in_time(double) [0x561c679cfe3f]
main_with_rev_string.d:747 _Dmain [0x561c679d7a40]
----- End exception message -----
Integration stopped: An exception was caught during the time step.
Done integrate_in_time().
Note that integrate_in_time failed.
Finalize the simulation.
Write flow solution.
Step= 1 final-t= 1e-10
Done.

**Comment by pajacobs-ghub** [comment]
Xinke,
With the latest couple of commits to the cyl.lua script, it is working for me, although it does report that it has trouble with flow conditions in a few cells.  It does, however, get the calculation done.
Regards,
Peter J.
![cyl-N-massf](https://github.com/gdtk-uq/gdtk/assets/62410919/75d872b1-63be-44e2-8517-d1d5c0dc5d8a)
![cyl-T-field](https://github.com/gdtk-uq/gdtk/assets/62410919/0dc7c4ec-52d9-43e6-ab53-ab4cc465a2cf)
