### ISSUE TITLE
Typo in User Guide, related to modal energy source terms

### ISSUE THREAD

**Issue by uqngibbo** [gdtk-uq/gdtk#36]
Alexis Lefevre has discovered that the User Guide section on user defined source terms does not match the code.

Specifically the guide tells users to add the following keys to the table that gets passed upstairs to the D code:

- **renergies** table of nmodes energy fluxes.
- **romega** rate of addition of ω for the k − ω turbulence model
- **rtke** rate of addition of turbulent kinetic energy

In getUDFSourceTermsForCell in user_defined_source_terms.d however, the D code looks for keys without the "r". Commit 40b9c0c4046baaed4421512bcfdb13e90839a130 to the gdtk-docs repo changes the text to the following:

 - **energies** table of nmodes energy fluxes.
 - **omega** rate of addition of ω for the k − ω turbulence model
 - **tke** rate of addition of turbulent kinetic energy
 - **nuhat** rate of addition of Spalart-Allmaras field variable

**Comment by uqngibbo** [comment]
Even though this issue is technically "fixed", we need to communicate this to users who may have saved versions of the PDF user guide.

**Comment by rjgollan-on-github** [comment]
The latest version of the User Guide PDF with Nick's amendments has been pushed up to the web server.

**Comment by uqngibbo** [comment]
This was addressed at a recent users meeting. Thanks Alexis for finding it!
