### ISSUE TITLE
header lines not written when config.write_loads is false

### ISSUE THREAD

**Issue by uqngibbo** [gdtk-uq/gdtk#38]
Volker Hanneman from DLR has found that running the steady state solver with:

`config.write_loads=false`
`write_loads_count = 100,`

Produces a malformed "times" file in the loads directory, which breaks some scripts for reading loads. Specifically this occurs because the header line is written during init_simulation, which honours the write_loads flag, but the loads files are written in steadystate_core, which does not.

**Comment by Alex-Muirhead** [comment]
Would this modification to [Line 1106 of `eilmer/steadystate_core.d`](https://github.com/gdtk-uq/gdtk/blob/7849fba32bc369c508d244f05f841b5ff3ffedc0/src/eilmer/steadystate_core.d#L1106C22-L1106C22) fix the issue?

```diff
// write out the loads
- if (!dual_time_stepping &&  ( (step % writeLoadsCount) == 0 || finalStep || step == GlobalConfig.write_loads_at_step )) {
+ if (!dual_time_stepping && GlobalConfig.write_loads && ( (step % writeLoadsCount) == 0 || finalStep || step == GlobalConfig.write_loads_at_step )) {
    if (GlobalConfig.is_master_task) {
```

**Comment by uqngibbo** [comment]
That's one option. We were discussing always writing the times header file or perhaps removing write_loads completely, and relying on a positive value for writeLoadsCount and dt_loads.

**Comment by uqngibbo** [comment]
There wasn't much a consensus so I haven't done anything about this yet.

**Comment by uqngibbo** [comment]
Fixed in eilmer 5
