### ISSUE TITLE
Nightmare bug in complex pow when given negative exponent.

### ISSUE THREAD

**Issue by uqngibbo** [gdtk-uq/gdtk#40]
The pow overload in complex.d current uses a for loop when called with an integer exponent, which causes it to return instantly when given a negative exponent:

```
number x = 10.0;
T = pow(x, -2)
writefln("T %e ", T)
>>>  10.0
```
This was causing all kinds of trouble in the old 2T argon model, and might be a problem elsewhere.

**Comment by kyleadm** [comment]
Commit [0aa0702](https://github.com/gdtk-uq/gdtk/commit/0aa070203fcb5f0b89adf8ff390b79968a9d189e) should fix this issue.

The routines now correctly return:
```
number x = 10.0;
number T = pow(x, -2)
writefln("T %e ", T)
>>>  T 1.000000e-02-0.000000e+00i 
```
