### ISSUE TITLE
Boundary conditions for T_modes

### ISSUE THREAD

**Issue by gianmarioperrucci** [gdtk-uq/gdtk#47]
Hello,
I'm having trouble applying a condition to the T_modes. 

I'm using as boundary condition "WallBC_NoSlip_UserDefinedT:new{Twall="BC_temp.lua"}", 
where BC_temp.lua contains:

function interface(args)
   elem = sampleFluidFace('u',blkId,args.i,0,0) --unstructured 2d grid
   Twall = 300
   inter = {}
   inter.T = Twall
   inter.T_modes = {Twall}
   inter.massf = elem.massf
   return inter
end

I read in other test cases that you need just to define inter.T and inter.T_modes, but without providing also the massflow the simulation does not start because of nan in the concentrations. 

Thank you for the help.

**Comment by uqngibbo** [comment]
Hi Gianmario,

This was in fact a bug, thanks for finding it. I've fixed it in e74443709eb32b46bc3ef49d6a85188f78ae357c.

You should be okay to keep running with setting the mass fractions manually, but it shouldn't crash if that isn't done anymore.

Nick,
