### ISSUE TITLE
Boundary load problem

### ISSUE THREAD

**Issue by KulaLAForU** [gdtk-uq/gdtk#51]
Hello,

I'm first time been using this amazing software but facing some problems now, currently using extract-boundary-loads method in 2temperature model, it would be great if it could extract the q_rot and q_tr separately by using  extract-boundary-loads method, is there any method to do so?

Thanks for your help,
Jianshu Wu

**Comment by uqngibbo** [comment]
Hi Jianshu,

Unfortunately there isn't an easy way to do this. The code for computing k_tr and k_rot is in the file src/gas/diffusion/multi_temperature_trans_props.d, so you might be able to adapt it into a python script for computing them in postprocessing.

That's probably what I would do.

Nick,

**Comment by KulaLAForU** [comment]
Thanks Nick,
Have a good day!
