### ISSUE TITLE
Import su2 mesh issue

### ISSUE THREAD

**Issue by KulaLAForU** [gdtk-uq/gdtk#54]
Hi again,

Sorry for this but I don't imagine this will come out and I cannot find how to fix it...
With import file 
<img width="1259" alt="Screenshot 2024-03-09 at 17 03 44" src="https://github.com/gdtk-uq/gdtk/assets/40930186/90c5d9d1-97d5-4755-94a3-55e032b53519">

but 
<img width="1400" alt="Screenshot 2024-03-09 at 17 00 28" src="https://github.com/gdtk-uq/gdtk/assets/40930186/9f8afb7d-ece1-47d8-9ca2-e31812badbd9">

And here is the mesh and input file:
[mesh_and_input.zip](https://github.com/gdtk-uq/gdtk/files/14545746/mesh_and_input.zip)

And I have a question: can Eilmer4 import su2 mesh with structure mesh?

Thanks very much for everything
Jianshu Wu

**Comment by rjgollan-on-github** [comment]
Hi Jianshu,
I took a look at your input script and there look to be some incompatibilities with what you're requesting of the program. It looks like you have shock-fitting requested. This **_only_** works with structured grids.

Here's some suggestions.

1. For getting the unstructured grid to work, just try a simple gas model (like ideal air). Check very carefully that the MARKER_TAG entries in your SU2 file have boundary conditions listed in the Eilmer file. For example, your SU2 lists "wall" but in Eilmer you put this in ALL CAPS as "WALL". You also have some MARKER_TAGs in the SU2 that are not set.
2. If you are interested in the Nonaka sphere case, I suggest using the Eilmer-native structured grids and following that example.

To answer your question: we cannot import an unstructured mesh and convert to a structured block even if all elements are quads. We don't have the information about its regular structure. We can go the other direction: structured --> unstructured.

**Comment by KulaLAForU** [comment]
Thank you!! It's really helping me a lot!!
Have a good day!!!
