### ISSUE TITLE
Question on staged prep option

### ISSUE THREAD

**Issue by jr144393** [gdtk-uq/gdtk#55]
I am wondering about how to invoke the staged prep options properly in Eilmer, as it would be extremely beneficial to my current runs. I have used the example in the sharp-cone-20-degrees, specifically the usg-su2 staged prep case, but I have a few challenges when extending this to my case. In my case, I encounter a mapped cell file issue. 

So in the present case, I have the ugrid partitioned su2 files, and I use the prep grid and prep flow format, but I encounter this issue: 

 "globalconfig.FlowSolverException@bc/ghost_cell_effect/mapped_cell_copy.dglobalconfig.FlowSolverException@bc/ghost_cell_effect/mapped_cell_copy.d(233): Did not find mapped blocks section for block id=175"

Is this because of a setting I need to adjust? I have noticed when I perform the e4shared --prep-grid --job="" command, it outputs the importing values and at the end states: 

\#connections: 0 
\#grids: 1280
\#gridArrays: 0 

So it appears maybe it is not identifying the connections. The grid is a pointwise generated su2 grid, and not a gridpro grid, would that cause this?

**Comment by uqngibbo** [comment]
Hi jr,

Staged prep is not very well tested in Eilmer 4, especially for unstructured grids. I'd recommend against using it for the time being.

Nick,

**Comment by jr144393** [comment]
Thank you for the reply.
