### ISSUE TITLE
Adjoint solver for design optimisation

### ISSUE THREAD

**Issue by abhx7** [gdtk-uq/gdtk#66]
How do I use install the executable for for adjoint solver to calculate shape sensitivities? It has been commented out in the Makefile.

**Comment by uqngibbo** [comment]
Hi abhx7,

I'm afraid the adjoint solver from Eilmer 4 has been depreciated: It was built as an experiment and even though it worked, it was too restrictive for general use.

A new shape optimisation code is currently being tested for Eilmer v5 that will be available in the near future, but at present it is not quite ready.

Nick,

**Comment by uqngibbo** [comment]
I should mention that, if you don't have too many design variables, it is still perfectly possible to compute sensitivites using finite differences if you have to!

**Comment by abhx7** [comment]
Alright, thank you. I was planning to use finite difference if i couldn't use the adjoint solver.

**Comment by rjgollan-on-github** [comment]
For a small number of design variables, this is likely a tractable approach.
