### ISSUE TITLE
How do i change the surface roughness of the shock tube for L1D4 simulation?

### ISSUE THREAD

**Issue by pmk3107** [gdtk-uq/gdtk#67]
I'm working as a intern in a shock tube lab. I would like to replicate the flow inside our shock tube using L1D4 simulation.

**Comment by uqngibbo** [comment]
Hi pmk,

Have a look at the reference manual on our website: https://gdtk.uqcloud.net/docs/l1d/l1d-reference-manual-for-hugo/

And then the examples in the repository: https://github.com/gdtk-uq/gdtk/tree/master/examples/l1d

L1D doesn't have an explicit factor for the surface roughness, but you should be able to add viscous patches and tune the parameters to match whatever you are seeing in your experiments.

Nick,

**Comment by pmk3107** [comment]
Thank you so much for the guidance, Nick.
