### ISSUE TITLE
Turbulent prandtl number

### ISSUE THREAD

**Issue by jr144393** [gdtk-uq/gdtk#73]
Is the turbulent prandtl number calculated locally? Based on each cell? Some studies have shown this  is necessary and I am curious if that is the case in eilmer currently. Thank you!

**Comment by uqngibbo** [comment]
Hi jr,

The turbulent prandtl number is fixed for the entire simulation. By default the number is 0.89, however this can be changed in the config.

I am aware there is some work in this space for improving heat transfer predictions. If you find anything interesting please let us know.

Nick,
