### ISSUE TITLE
Reinitialize simulation

### ISSUE THREAD

**Issue by jr144393** [gdtk-uq/gdtk#74]
Is it possible to reinitialize a simulation that used one set of species to another? I am trying to initialize a 5sp air script from an ideal air script (same domain). So far, the response from the code is:  

Error in call to makeFlowStateFromTable.Length of T_modes vector does not match number of modes in gas model.T_modes.length= 0; n_modes= 1

This would make sense since the ideal air sim does not have a modal temperature set. Does someone have advice for this? Perhaps the other option is to start with the 5sp model but with reactions turned off?

**Comment by uqngibbo** [comment]
Unfortunately not at the moment. One day we will have a script for converting an completed solution to a different gas model but no-one has made one yet, that I am aware of.

**Comment by jr144393** [comment]
Okay, I have another solution that works, which is just running with the reaction time delay active for a bit before turning chemical reactions on. 

Thank you!
