### ISSUE TITLE
A question about SU2 Mesh Import Procedure in Eilmer v5 

### ISSUE THREAD

**Issue by plaad** [gdtk-uq/gdtk#76]
Hi all,

I have been able to import and use SU2 grids in v4 no problem and  have been following some of the unstructured grid import examples to similarly proceed in v5/lmr but am coming across a slight issue. Namely, I am following the procedure in the oblique detonation wave example where the SU2 file is now processed in the importgrid.lua:

nblocks = 4
grids = {}
for i=0,nblocks-1 do
   fileName = string.format("su2grid/block_%d_grid.su2", i)
   registerFluidGrid{grid=UnstructuredGrid:new{filename=fileName, fmt='su2text'},fsTag='inflow'}
end

Being said I was able to run this example case fine and applied a similar logic to my imported 3D grid and the output is:

Begin partitioning................

-- -- Import SU2 mesh
-- -- -- Found boundary i=0 tag=WALLS
-- -- -- Found boundary i=1 tag=INFLOW
-- -- -- Found boundary i=2 tag=OUTFLOW
-- -- -- Found boundary i=3 tag=SYMMETRY
-- -- -- Found boundary i=4 tag=PER1
-- -- -- Found boundary i=5 tag=PER2
-- -- -- Found boundary i=6 tag=FLUID
-- Converting SU2 mesh to Metis mesh format
-- Converting mesh to dual format
-- Partitioning dual format
-- Building 4 blocks in SU2 format
-- -- Reading Metis output file
-- -- Reading cell interconnectivity from dual format file
-- -- Data reading complete, proceed to building blocks
-- Writing out block: #0
-- Writing out block: #1
-- Writing out block: #2
-- Writing out block: #3
Finished partitioning................
Species database loaded from:   /work/sidgs/partth/codes/eilmer/install/data/species-database.lua
Importing: su2grid/block_0_grid.su2 ... (done) scale=1 dim=3 ncells=8613 nbfs= 6
There was a problem in the user-supplied input lua script: importgrid.lua
globalconfig.FlowSolverException@./commands/prepgrids.d(93): /work/sidgs/partth/codes/eilmer/install/lib/grid.lua:79: bad argument #1 to 'get_dimensions' (UnstructuredGrid expected, got no value)
----------------
  ./commands/prepgrids.d:93 int prepgrids.main_(immutable(char)[][]) [0xaed3f0]
main.d:165 _Dmain [0xeeb40e]
Read Grid Metadata.
There was a problem in the Eilmer build function readGridMetadata() in prepsim.lua

My run script is as follows:

rm -rf lmrsim
rm -rf mapped-cells  su2grid
mkdir su2grid
cp expramp10.su2 su2grid/grid.su2

cd su2grid
ugrid_partition grid.su2 mapped_info.txt 4 3
cp mapped_info.txt ../mapped-cells
cd ..

mkdir -p lmrsim
cp mapped-cells  lmrsim/mapped-cells
lmr prep-gas -i ideal-air.inp -o lmrsim/ideal-air.lua
lmr prep-grid -j importgrid.lua
lmr prep-sim
    
mpirun -np 4 lmrZ-mpi-run

and the only commands in my input deck pertaining to the fluid blocks are:

bcDict = {WALLS            = WallBC_WithSlip0:new{},
          INFLOW         = InFlowBC_Supersonic:new{flowCondition=inflow},
          OUTFLOW        = OutFlowBC_Simple:new{},
          SYMMETRY         = WallBC_WithSlip0:new{},
          PER1             = WallBC_WithSlip0:new{},
          PER2           = WallBC_WithSlip0:new{},
          METIS_INTERIOR = ExchangeBC_MappedCell:new{cell_mapping_from_file=true,list_mapped_cells=false}}

flowDict = {inflow = inflowState}
makeFluidBlocks(bcDict, flowDict)

where I define the inflowState to be my FlowState object and such. It seems to process the partitioned block, but the importgrid.lua script is not working in this case. The SU2 file and the partition process is detecting the correct grid dimension so I am not sure where the bad argument #1 is coming from. Perhaps this has to do with the way my SU2 file is made? I am using GMSH to make my grid, but in the example, a script  generated the SU2 file.

Are there any things I am doing incorrectly in my prep-grid routine/how I am proceeding?  Perhaps my mapped-cells file is not set properly to be found  during runtime? Apologies if I missed something trivial in my setup.

**Comment by uqngibbo** [comment]
Hi plaad,

Can you try adding
```
config.dimensions = 3
```
to your importgrid and job lua scripts? That error message is broken but I it's suppposed to check that the config.dimensions matches the imported grid.

**Comment by plaad** [comment]
This did the trick; thanks for letting me know. In retrospect, it makes sense to define the dimensions in the importgrid.lua file as it is being accessed as a standalone script. Everything is working properly now. Thank you.

**Comment by uqngibbo** [comment]
I have fixed this error message in 453ec813 so that it works properly. Thanks for finding this.
