### ISSUE TITLE
Appears to be an interior face

### ISSUE THREAD

**Issue by jessowy** [gdtk-uq/gdtk#79]
Hi,

I am trying to do mesh and shock refinement which include having interior surfaces generated in the domain. I have set the interior surfaces with a boundary marker matching with ExchangeBC_MappedCell:new{list_mapped_cells=true} but error occurred showing 
Importing: su2grid/block_0_mesh.su2 ...geom.geometry_exception.GeometryException@../geom/grid/usgrid.d(1733): appears to be an interior face
Is there a way to forcefully remove the surface or am I using the wrong boundary condition. 

Your help is much appreciated. Thank you.

**Comment by rjgollan-on-github** [comment]
In short: you might be doing something wrong. However, I need more information to figure this out.

Could you:

1. Upload a sketch of your geometry AND the blocking topology (this will help me determine what interior surfaces you have and what is needed there); and
2. describe how you generated the grid: eilmer-native grid? 3rd-party generated grid? structured grids? unstructured grids?

Long answer: mostly we don't need to micro-manage internal connections. We typically use identify_grid_connections (v5)/identify_block_connections (v4) to handle the setting of internal connections. Or, in the case of a partitioned unstructured grid, we'll usually set the ExchangeBC_MappedCell to point to a file that contains the connections on a cell-by-cell basis.

**Comment by jessowy** [comment]
Hi,

Thanks for the reply, it was found to be some tiny mistake during the grid generation process. It is fine at the moment.
