### ISSUE TITLE
Quick questions about Lua scripting for probes in lmr, multispecies solver behavior, and MHD/multiphase modeling capabilities

### ISSUE THREAD

**Issue by plaad** [gdtk-uq/gdtk#83]
Hi All,

I just had a few quick questions:

1) I was setting up a 0D, finite volume reactor similar to the example used in the reactor-n2 example case with a probe. In the input script of an older example, there was scripting to allow one to probe the time history of various variables to an output file. I tried to use the same logic in my code and pass the variable: 

In my input script:
`_gs= setGasModel('nitrogen-2sp.lua')`
`config.reacting = true`
`config.reactions_file = 'chem.lua'`
`config.gasdynamic_update_scheme = 'backward_euler'`
`config.chemistry_update = 'integral' -- other option is 'split'`
`_gs.p = 1.0e5`
`_gs.T = 4000.0`
`_gs.massf ={N2=0.8, N=0.2}`
`initiall = FlowState:new{p=_gs.p, T=_gs.T, massf=_gs.massf}`

and the main probe is given:

`f = assert(io.open("fvreactor.data", 'w'))`
`f:write('# 1:t(s)  2:T(K)  3:p(Pa)  4:massf_N2  5:massf_N  6:conc_N2  7:conc_N\n')`
`f:write(string.format("%10.3e %10.3f %10.3e %20.12e %20.12e %20.12e %20.12e\n",`
`                      t, _gs.T, _gs.p, _gs.massf.N2, _gs.massf.N, conc.N2, conc.N))`
`while t <= config.max_time do`
`   -- dtSuggest = chemUpdate:updateState(gs, dt, dtSuggest, gm)`
`   t = t + dt`
`   --dt = dtSuggest -- uncomment this to get quicker stepping`
`   gm:updateThermoFromRHOU(_gs)`
`   conc = gm:massf2conc(_gs)`
`   f:write(string.format("%10.3e %10.3f %10.3e %20.12e %20.12e %20.12e %20.12e\n",`
`                         t, _gs.T, _gs.p, _gs.massf.N2, _gs.massf.N, conc.N2, conc.N))`
`end`
`f:close()`
where config.max_time is set in another line. Is there something I am missing/different for the implementation in v5 vs v4?

2) For a multispecies, reacting flow case I have followed a 1-step irreversible reaction with nonreactive species A entering an inflow boundary by first running a non-reactive case to steady state; thereafter, I enabled reacting flows to convert species A to B irreversibly and it seems to be partially working. I had expected all of species A to convert to B, but it seems to be reaching an equilibrium state where the mass fraction of A goes from 1.0 -> 0.5 and B goes from 0.0 -> 0.5. How can I fix this so the reaction proceeds correctly? Some additional points:

-     My species are identical but the enthalpy of formation of each is varied to supply heat release from the 1 step reaction and they are defined in their respective gas.lua files; I am using the thermally perfect gas model for both species. 
-     The reaction details are `Reaction{' A + A => B + B',fr={'Arrhenius', A=1.413e13, n=0, C=19012.4},label='r1'}`
-     When restarting from the last snapshot (non-reactive), does one need to perform the lmr prep-gas, prep-chem steps upon restart? I would think not but I am not sure. I just do not know why the species are equilibrating instead of being fully converted to B after the reaction begins. My mechanism is formatted for only a forward rate enabled so this should not be an issue.
-      Can you explain how chemistry is updated if using either the 'integral' or 'split' options? Does the 'split' option refer to Strang splitting; else can you explain how lmr/eilmer performs this?

Any and suggestions as to why this is happening? See my related post #82  about a possible bug/issue in the Roe scheme.

3)  I understand there is support for MHD, but are there any additional methods for simulating ionization/plasma? I saw there was a three-temperature model, but I could not find any reference to theory as to what options are available for ionizing flows/plasma modeling if you can point me to one and what options I would need to use to try this. I would think multispecies, reactive air would be for ionization but I am unsure if there are other means for plasma modeling.

4) On this note, does Eilmer have any support for multiphase modeling at the current state? I thought I saw something in the past for multiphase but I may be mistaken. If so can you point me to an example/paper I can similarly study and look into for further details. 

Thank you.

**Comment by rjgollan-on-github** [comment]
1. You changed too much from the original script. We use "gm" as the gas model variable and "gs" as the gas state variable. You seem to use _gs for both. There's a line you set a model to _gs and then later you try to push state values in to _gs. I suggest starting again and modifying on step at a time.

2. (a) The generalised chemistry will only handle irreversible reactions if you explicitly set the backwards rate to 0.
    (b) see 2(a)
    (c) No. prep-gas and prep-chem are typically one-time initial steps. They set the Eilmer-ready inputs for gas and chemistry. On a restart, Eilmer is reading from the JSON config file; that contains the gas and chemistry file names.
    (d) 'integral' and 'split' options are relatively new and haven't made it to the Reference Manual. I will add these. Yes, 'split' relates to operator-splitting or Strang-splitting. For more details, see the final paragraph in left colum on page 8 of Gibbons et al (2023) https://doi.org/10.1016/j.cpc.2022.108551
    (e) Not approaching the equilibrium you expect is likely because 2(a). The Roe scheme relates to fluid motion and is independent of the thermochemical behaviour at a point.

3. There is implementation for MHD but not support. We are not funded to support that breadth of modelling capability. Please see Release Notes for core support capabilities: https://gdtk.uqcloud.net/docs/eilmer/releases/#version-400

Similarly, the multi-temperature modelling isn't part of core features. It won't be until the conclusion of Robert Watt's thesis, once we've had time to make the implementation robust for a variety of uses cases. You are free to read a description of it here: https://www.afms.org.au/proceedings/23/Watt_et_al_2022.pdf

4. There is no multi-phase fluid implementation currently. In the past, there was some modelling of supercritical fluids (if one counts that as multi-phase). However, we are not funded to continue work in that area.

**Comment by rjgollan-on-github** [comment]
Description of `config.chemistry_update` has been added to Reference Manual now: https://gdtk.uqcloud.net/docs/eilmer/eilmer-reference-manual/#_finite_rate_thermo_chemistry

**Comment by plaad** [comment]
Thank you so much for the clarification on these matters. This helps and I should be good to go.
