### ISSUE TITLE
Stagnation inflow boundary condition incompatible with two temp models

### ISSUE THREAD

**Issue by Jashby792** [gdtk-uq/gdtk#9]
The 2T gas model appear to be incompatible with the InFlowFromStagnation_BC

**Comment by uqngibbo** [comment]
Fixed in 25dbc9e7 and cdc450f7. 

Please let me know if there are any troubles with this, and make sure to use the general TwoTemperatureGas model, not any of the legacy models like TwoTemperatureAir.
